version: '3.8'

services:
  server_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: iqura_study/server_api:latest
    ports:
      - "7080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LocalConnection=Host=database;Database=IquraStudyDB;Username=postgres;Password=postgres
    volumes:
      - .:/app
    depends_on:
      - database
    restart: always

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: IquraStudyDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database
    restart: always

volumes:
  pgdata:
  pgadmin-data: 
